default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: emono_development


test:
  <<: *default
  database: emono_test


production:
  <<: *default
  database: emono_production
  username: emono
  password: <%= ENV['EMONO_DATABASE_PASSWORD'] %>
